phpunit update
zendframework/zend-mvc-i18n pull request #14
Opened 2017-08-20 17:30 UTC by kokspflanze

- PHPUnit_Framework_TestCase changed to PHPUnit\Framework\TestCase
- getMock changed to createMock
- updated min phpunit version
- updated composer.lock, with latest phpunit version
- updated travis build, with phpunit as build param

2017-08-23 20:45 UTC, michalbundyra requested changes

2017-08-23 20:45 UTC, webimpress commented on .travis.yml
> +  - if [[ $CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi
Why these lines are changed? Why you are not using composer scripts defined in `composer.json` ?

2017-08-23 20:45 UTC, webimpress commented on .travis.yml
> +  - composer show
We should have here `stty cols 120 && composer show`

2017-08-23 21:05 UTC, kokspflanze commented on .travis.yml
> +  - if [[ $CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi
i rechanged i, with my latest commit to the [template](https://github.com/zendframework/maintainers/blob/master/template/.travis.yml) @froschdesign gave me the link

2017-08-23 21:05 UTC, kokspflanze commented on .travis.yml
> +  - composer show
changed to the template

2017-08-23 21:06 UTC, webimpress commented on composer.json
> +        "phpunit/phpunit": "^5.7.21 || ^6.3.0",
It's not too important, but we don't need `.0` in `6.3.0`, please note we have it like that for other packages, for example:
`"zendframework/zend-validator": "^2.6"`
not:
`"zendframework/zend-validator": "^2.6.0"`

2017-08-24 06:55 UTC, michalbundyra requested changes
I think we need here still modifications in Travis configuration to work with legacy dependencies. Currently library supports PHP 5.6 and PHP 7+.  As far as I know `travis.yml` from maintainers template is for libraries which supports only PHP 7.1+

2017-08-24 06:55 UTC, webimpress commented on .travis.yml
> +    - COVERAGE_DEPS="satooshi/php-coveralls"
We need legacy dependencies here.

2017-08-24 18:39 UTC, kokspflanze commented on .travis.yml
> +    - COVERAGE_DEPS="satooshi/php-coveralls"
im working on it but it will take some time, i have many open prs, with that case

2018-05-01 15:30 UTC, merged